In [1]:
# ==========================================================
# PFE ESB
# Notebook 03
# Data Preprocessing
# ==========================================================

import pandas as pd
import numpy as np

from pathlib import Path

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows",100)

In [2]:
# ==========================================================
# PATHS
# ==========================================================

BASE_DIR = Path.cwd().parent

RAW_DATA = BASE_DIR / "data" / "raw"

OUTPUT = BASE_DIR / "outputs"

OUTPUT.mkdir(exist_ok=True)

print(BASE_DIR)

c:\Users\Sarra\OneDrive\Desktop\PFE_CHURN_ESB

In [3]:
# ==========================================================
# LOAD DATASET
# ==========================================================

df = pd.read_csv(

    RAW_DATA / "DATA (1).csv",

    encoding="utf-8-sig",

    sep=";"

)

df.columns = (
    df.columns
    .str.replace("ï»¿","",regex=False)
    .str.strip()
)

print(df.shape)

df.head()

(528884, 34)

,CUSTOMER_NO,ACCOUNT_NO,NATIONALITY,RESIDENCE,MARITAL_STATUS,CUST_OPENING_DATE,DATE_OF_BIRTH,NATURE_CLIENT,BRANCH,SCORE_KYC,COMPLETED_FILE,LAST_REVIEW_DATE,NEXT__REVIEW_DATE,ACCOUNT_STATUS,ACCT_OPENING_DATE,ACCOUNT_CATEGORY,ACCOUNT_TYPE_DESC,CURRENCY,ACCT_CLOSE_DATE,CLOSURE_REASON,ACCT_BALANCE,INDUSTRY,SALARY,PRODUCT_GROUP,PRODUCT_LINE,PRODUCT,ACCOUNTNATURE,STARTDATE,MATURITYDATE,AMOUNT,FIXEDRATE,PRODUCT_STATUS,PARTYCLASS,LOB
0,113772024,2.012013e+09,TN,TN,M,20040930.0,19690529.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20190827.0,3023.0,Crédit acquisition logement TEGF6,TND,20260128.0,NaN,-10714.347,9000,2725.739,RT.CRD.IMMOBILERS,LENDING,RT.RT.CRD.IMMOBILERS.527,Crédit acquisition logement TEGF6,1251227.0,1290627.0,10954600.0,4.5,CURRENT,Retail,4
1,113772022,2.012119e+09,TN,TN,M,20040930.0,19600923.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20260105.0,3611.0,DEPOTS A TERME,TND,20250630.0,NaN,0.000,9000,3300.537,ATB.PLACEMENT.NEG,DEPOSITS,ATB.CAT.NEG.SIM,DEPOTS A TERME,20260102.0,NaN,NaN,NaN,UNAUTH,Retail,4
2,113772024,2.011691e+09,TN,TN,M,20040930.0,19690529.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20230612.0,3017.0,Crédit rénovation,TND,20260128.0,NaN,-113033.101,9000,2725.739,RT.CRD.IMMOBILERS,LENDING,RT.RT.CRD.IMMOBILERS.548,Crédit rénovation,1251227.0,1380527.0,113593077.0,4.5,CURRENT,Retail,4
3,113772024,2.010055e+09,TN,TN,M,20040930.0,19690529.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20220527.0,1011.0,Compte Allocation Touristique TND,TND,20260128.0,NaN,0.000,9000,2725.739,ATB.GRP.CUR.ACCT,ACCOUNTS,ATB.CUR.ACCT.ALL.TOURS.CARTE,Compte Allocation Touristique TND,NaN,NaN,0.0,NaN,NaN,Retail,4
4,113772022,2.011092e+09,TN,TN,M,20040930.0,19600923.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20250702.0,3611.0,DEPOTS A TERME,TND,20250630.0,NaN,0.000,9000,3300.537,NaN,NaN,NaN,DEPOTS A TERME,NaN,NaN,NaN,NaN,NaN,Retail,4

In [4]:
print("="*70)

print("DATASET")

print("="*70)

print()

print("Rows :",len(df))

print("Columns :",len(df.columns))

print()

display(df.head())

print()

display(df.dtypes)

======================================================================
DATASET
======================================================================

Rows : 528884
Columns : 34

,CUSTOMER_NO,ACCOUNT_NO,NATIONALITY,RESIDENCE,MARITAL_STATUS,CUST_OPENING_DATE,DATE_OF_BIRTH,NATURE_CLIENT,BRANCH,SCORE_KYC,COMPLETED_FILE,LAST_REVIEW_DATE,NEXT__REVIEW_DATE,ACCOUNT_STATUS,ACCT_OPENING_DATE,ACCOUNT_CATEGORY,ACCOUNT_TYPE_DESC,CURRENCY,ACCT_CLOSE_DATE,CLOSURE_REASON,ACCT_BALANCE,INDUSTRY,SALARY,PRODUCT_GROUP,PRODUCT_LINE,PRODUCT,ACCOUNTNATURE,STARTDATE,MATURITYDATE,AMOUNT,FIXEDRATE,PRODUCT_STATUS,PARTYCLASS,LOB
0,113772024,2.012013e+09,TN,TN,M,20040930.0,19690529.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20190827.0,3023.0,Crédit acquisition logement TEGF6,TND,20260128.0,NaN,-10714.347,9000,2725.739,RT.CRD.IMMOBILERS,LENDING,RT.RT.CRD.IMMOBILERS.527,Crédit acquisition logement TEGF6,1251227.0,1290627.0,10954600.0,4.5,CURRENT,Retail,4
1,113772022,2.012119e+09,TN,TN,M,20040930.0,19600923.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20260105.0,3611.0,DEPOTS A TERME,TND,20250630.0,NaN,0.000,9000,3300.537,ATB.PLACEMENT.NEG,DEPOSITS,ATB.CAT.NEG.SIM,DEPOTS A TERME,20260102.0,NaN,NaN,NaN,UNAUTH,Retail,4
2,113772024,2.011691e+09,TN,TN,M,20040930.0,19690529.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20230612.0,3017.0,Crédit rénovation,TND,20260128.0,NaN,-113033.101,9000,2725.739,RT.CRD.IMMOBILERS,LENDING,RT.RT.CRD.IMMOBILERS.548,Crédit rénovation,1251227.0,1380527.0,113593077.0,4.5,CURRENT,Retail,4
3,113772024,2.010055e+09,TN,TN,M,20040930.0,19690529.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20220527.0,1011.0,Compte Allocation Touristique TND,TND,20260128.0,NaN,0.000,9000,2725.739,ATB.GRP.CUR.ACCT,ACCOUNTS,ATB.CUR.ACCT.ALL.TOURS.CARTE,Compte Allocation Touristique TND,NaN,NaN,0.0,NaN,NaN,Retail,4
4,113772022,2.011092e+09,TN,TN,M,20040930.0,19600923.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20250702.0,3611.0,DEPOTS A TERME,TND,20250630.0,NaN,0.000,9000,3300.537,NaN,NaN,NaN,DEPOTS A TERME,NaN,NaN,NaN,NaN,NaN,Retail,4

CUSTOMER_NO            int64
ACCOUNT_NO           float64
NATIONALITY              str
RESIDENCE                str
MARITAL_STATUS           str
CUST_OPENING_DATE    float64
DATE_OF_BIRTH        float64
NATURE_CLIENT            str
BRANCH                 int64
SCORE_KYC                str
COMPLETED_FILE           str
LAST_REVIEW_DATE     float64
NEXT__REVIEW_DATE    float64
ACCOUNT_STATUS           str
ACCT_OPENING_DATE    float64
ACCOUNT_CATEGORY     float64
ACCOUNT_TYPE_DESC        str
CURRENCY                 str
ACCT_CLOSE_DATE      float64
CLOSURE_REASON           str
ACCT_BALANCE         float64
INDUSTRY               int64
SALARY               float64
PRODUCT_GROUP            str
PRODUCT_LINE             str
PRODUCT                  str
ACCOUNTNATURE            str
STARTDATE            float64
MATURITYDATE         float64
AMOUNT               float64
FIXEDRATE            float64
PRODUCT_STATUS           str
PARTYCLASS               str
LOB                    int64
dtype: object

## 3.4 Data Type Correction

The raw dataset contains identifiers, categorical variables, numerical values and date fields stored as numeric values.

This step aims to:

- preserve identifiers as strings;
- convert date fields into datetime format;
- convert categorical variables into clean string values;
- keep financial variables as numerical values;
- detect invalid date formats without modifying the original source file.

In [5]:
# ==========================================================
# COLUMN GROUPS
# ==========================================================

identifier_columns = [
    "CUSTOMER_NO",
    "ACCOUNT_NO"
]

standard_date_columns = [
    "CUST_OPENING_DATE",
    "DATE_OF_BIRTH",
    "LAST_REVIEW_DATE",
    "NEXT__REVIEW_DATE",
    "ACCT_OPENING_DATE",
    "ACCT_CLOSE_DATE"
]

special_date_columns = [
    "STARTDATE",
    "MATURITYDATE"
]

categorical_columns = [
    "NATIONALITY",
    "RESIDENCE",
    "MARITAL_STATUS",
    "NATURE_CLIENT",
    "SCORE_KYC",
    "COMPLETED_FILE",
    "ACCOUNT_STATUS",
    "ACCOUNT_TYPE_DESC",
    "CURRENCY",
    "CLOSURE_REASON",
    "PRODUCT_GROUP",
    "PRODUCT_LINE",
    "PRODUCT",
    "ACCOUNTNATURE",
    "PRODUCT_STATUS",
    "PARTYCLASS"
]

numeric_columns = [
    "ACCT_BALANCE",
    "SALARY",
    "AMOUNT",
    "FIXEDRATE"
]

code_columns = [
    "BRANCH",
    "INDUSTRY",
    "LOB",
    "ACCOUNT_CATEGORY"
]

print("Identifiers          :", identifier_columns)
print("Standard dates       :", standard_date_columns)
print("Special-format dates :", special_date_columns)
print("Categorical          :", len(categorical_columns))
print("Numeric              :", numeric_columns)
print("Codes                :", code_columns)

Identifiers          : ['CUSTOMER_NO', 'ACCOUNT_NO']
Standard dates       : ['CUST_OPENING_DATE', 'DATE_OF_BIRTH', 'LAST_REVIEW_DATE', 'NEXT__REVIEW_DATE', 'ACCT_OPENING_DATE', 'ACCT_CLOSE_DATE']
Special-format dates : ['STARTDATE', 'MATURITYDATE']
Categorical          : 16
Numeric              : ['ACCT_BALANCE', 'SALARY', 'AMOUNT', 'FIXEDRATE']
Codes                : ['BRANCH', 'INDUSTRY', 'LOB', 'ACCOUNT_CATEGORY']

In [6]:
# ==========================================================
# WORKING COPY
# ==========================================================

df_clean = df.copy()

print("Original dataset :", df.shape)
print("Working copy     :", df_clean.shape)

Original dataset : (528884, 34)
Working copy     : (528884, 34)

In [7]:
# ==========================================================
# IDENTIFIER CONVERSION
# ==========================================================

for column in identifier_columns:
    df_clean[column] = (
        pd.to_numeric(df_clean[column], errors="coerce")
          .astype("Int64")
          .astype("string")
    )

display(df_clean[identifier_columns].head())

print(df_clean[identifier_columns].dtypes)

  CUSTOMER_NO  ACCOUNT_NO
0   113772024  2012012858
1   113772022  2012119377
2   113772024  2011690734
3   113772024  2010054933
4   113772022  2011091601

CUSTOMER_NO    string
ACCOUNT_NO     string
dtype: object

In [8]:
# ==========================================================
# SAFE YYYYMMDD DATE CONVERSION
# ==========================================================

def convert_yyyymmdd(
    series: pd.Series,
    min_year: int = 1900,
    max_year: int = 2100
) -> pd.Series:
    """
    Convert standard YYYYMMDD values into pandas datetime.

    Invalid formats, impossible calendar dates and years outside
    the accepted interval are converted to NaT.
    """

    cleaned = (
        series
        .astype("string")
        .str.replace(r"\.0$", "", regex=True)
        .str.strip()
    )

    valid_format = cleaned.str.fullmatch(r"\d{8}", na=False)

    years = pd.to_numeric(
        cleaned.str.slice(0, 4),
        errors="coerce"
    )

    valid_year = years.between(
        min_year,
        max_year,
        inclusive="both"
    )

    eligible = valid_format & valid_year
    safe_values = cleaned.where(eligible)

    return pd.to_datetime(
        safe_values,
        format="%Y%m%d",
        errors="coerce"
    )

In [9]:
# ==========================================================
# STANDARD DATE CONVERSION
# ==========================================================

date_conversion_report = []

for column in standard_date_columns:

    original_non_null = int(
        df_clean[column].notna().sum()
    )

    converted = convert_yyyymmdd(
        df_clean[column],
        min_year=1900,
        max_year=2100
    )

    valid_dates = int(converted.notna().sum())
    invalid_dates = original_non_null - valid_dates

    df_clean[column] = converted

    invalid_rate = (
        invalid_dates / original_non_null * 100
        if original_non_null > 0
        else 0
    )

    date_conversion_report.append({
        "Column": column,
        "Original Non-Null": original_non_null,
        "Valid Dates": valid_dates,
        "Invalid Dates Converted to NaT": invalid_dates,
        "Invalid Rate (%)": round(invalid_rate, 2)
    })

date_conversion_report = pd.DataFrame(
    date_conversion_report
)

display(date_conversion_report)

,Column,Original Non-Null,Valid Dates,Invalid Dates Converted to NaT,Invalid Rate (%)
0,CUST_OPENING_DATE,515262,515262,0,0.00
1,DATE_OF_BIRTH,427569,427542,27,0.01
2,LAST_REVIEW_DATE,501479,501479,0,0.00
3,NEXT__REVIEW_DATE,504302,504302,0,0.00
4,ACCT_OPENING_DATE,383959,383959,0,0.00
5,ACCT_CLOSE_DATE,221942,221942,0,0.00

In [10]:
# ==========================================================
# DATE CONVERSION VALIDATION
# ==========================================================

display(
    df_clean[standard_date_columns].head()
)

print("Converted date types:")
print(df_clean[standard_date_columns].dtypes)

print("\nSpecial-format date columns remain unchanged:")
print(df_clean[special_date_columns].dtypes)

,CUST_OPENING_DATE,DATE_OF_BIRTH,LAST_REVIEW_DATE,NEXT__REVIEW_DATE,ACCT_OPENING_DATE,ACCT_CLOSE_DATE
0,2004-09-30,1969-05-29,2025-09-05,2029-09-05,2019-08-27,2026-01-28
1,2004-09-30,1960-09-23,2025-09-05,2029-09-05,2026-01-05,2025-06-30
2,2004-09-30,1969-05-29,2025-09-05,2029-09-05,2023-06-12,2026-01-28
3,2004-09-30,1969-05-29,2025-09-05,2029-09-05,2022-05-27,2026-01-28
4,2004-09-30,1960-09-23,2025-09-05,2029-09-05,2025-07-02,2025-06-30

Converted date types:
CUST_OPENING_DATE    datetime64[us]
DATE_OF_BIRTH        datetime64[us]
LAST_REVIEW_DATE     datetime64[us]
NEXT__REVIEW_DATE    datetime64[us]
ACCT_OPENING_DATE    datetime64[us]
ACCT_CLOSE_DATE      datetime64[us]
dtype: object

Special-format date columns remain unchanged:
STARTDATE       float64
MATURITYDATE    float64
dtype: object

## 3.5 Missing Values Treatment

Missing values are treated according to their business meaning.

The strategy distinguishes between:

- structural missing values;
- missing customer information;
- missing account information;
- missing numerical values;
- missing categorical values.

No global deletion rule is applied.

In [11]:
# ==========================================================
# MISSING VALUES BEFORE TREATMENT
# ==========================================================

missing_before = pd.DataFrame({
    "Column": df_clean.columns,
    "Missing Before": df_clean.isna().sum().values,
    "Missing Before (%)": (
        df_clean.isna().mean() * 100
    ).round(2).values
})

display(
    missing_before.sort_values(
        "Missing Before (%)",
        ascending=False
    )
)

               Column  Missing Before  Missing Before (%)
30          FIXEDRATE          449335               84.96
28       MATURITYDATE          449333               84.96
31     PRODUCT_STATUS          436160               82.47
27          STARTDATE          436156               82.47
19     CLOSURE_REASON          385328               72.86
22             SALARY          326649               61.76
18    ACCT_CLOSE_DATE          306942               58.04
10     COMPLETED_FILE          239644               45.31
29             AMOUNT          223520               42.26
25            PRODUCT          208846               39.49
24       PRODUCT_LINE          208846               39.49
23      PRODUCT_GROUP          208846               39.49
26      ACCOUNTNATURE          144925               27.40
20       ACCT_BALANCE          144925               27.40
17           CURRENCY          144925               27.40
14  ACCT_OPENING_DATE          144925               27.40
16  ACCOUNT_TYPE_DESC          144925               27.40
15   ACCOUNT_CATEGORY          144925               27.40
4      MARITAL_STATUS          118698               22.44
6       DATE_OF_BIRTH          101342               19.16
13     ACCOUNT_STATUS           44440                8.40
1          ACCOUNT_NO           44440                8.40
11   LAST_REVIEW_DATE           27405                5.18
12  NEXT__REVIEW_DATE           24582                4.65
5   CUST_OPENING_DATE           13622                2.58
9           SCORE_KYC             845                0.16
7       NATURE_CLIENT              78                0.01
0         CUSTOMER_NO               0                0.00
8              BRANCH               0                0.00
3           RESIDENCE               0                0.00
2         NATIONALITY               0                0.00
21           INDUSTRY               0                0.00
32         PARTYCLASS               0                0.00
33                LOB               0                0.00

In [12]:
# ==========================================================
# MISSING VALUE STRATEGY
# ==========================================================

categorical_fill_unknown = [
    "MARITAL_STATUS",
    "NATURE_CLIENT",
    "SCORE_KYC",
    "COMPLETED_FILE"
]

structural_fill_not_applicable = [
    "ACCOUNT_STATUS",
    "ACCOUNT_TYPE_DESC",
    "CURRENCY",
    "CLOSURE_REASON",
    "PRODUCT_GROUP",
    "PRODUCT_LINE",
    "PRODUCT",
    "ACCOUNTNATURE",
    "PRODUCT_STATUS"
]

numeric_fill_median = [
    "SALARY"
]

numeric_keep_missing = [
    "ACCT_BALANCE",
    "AMOUNT",
    "FIXEDRATE"
]

print("Unknown category fill:", categorical_fill_unknown)
print("Not applicable fill:", structural_fill_not_applicable)
print("Median fill:", numeric_fill_median)
print("Keep missing:", numeric_keep_missing)

Unknown category fill: ['MARITAL_STATUS', 'NATURE_CLIENT', 'SCORE_KYC', 'COMPLETED_FILE']
Not applicable fill: ['ACCOUNT_STATUS', 'ACCOUNT_TYPE_DESC', 'CURRENCY', 'CLOSURE_REASON', 'PRODUCT_GROUP', 'PRODUCT_LINE', 'PRODUCT', 'ACCOUNTNATURE', 'PRODUCT_STATUS']
Median fill: ['SALARY']
Keep missing: ['ACCT_BALANCE', 'AMOUNT', 'FIXEDRATE']

In [13]:
# ==========================================================
# APPLY MISSING VALUE TREATMENT
# ==========================================================

for column in categorical_fill_unknown:
    df_clean[column] = (
        df_clean[column]
        .astype("string")
        .fillna("UNKNOWN")
    )

for column in structural_fill_not_applicable:
    df_clean[column] = (
        df_clean[column]
        .astype("string")
        .fillna("NOT_APPLICABLE")
    )

for column in numeric_fill_median:
    median_value = df_clean[column].median()
    df_clean[column] = df_clean[column].fillna(median_value)

print("Missing value treatment applied.")

Missing value treatment applied.

In [14]:
# ==========================================================
# MISSING VALUES AFTER TREATMENT
# ==========================================================

missing_after = pd.DataFrame({
    "Column": df_clean.columns,
    "Missing After": df_clean.isna().sum().values,
    "Missing After (%)": (
        df_clean.isna().mean() * 100
    ).round(2).values
})

missing_comparison = missing_before.merge(
    missing_after,
    on="Column",
    how="left"
)

display(
    missing_comparison.sort_values(
        "Missing Before (%)",
        ascending=False
    )
)

,Column,Missing Before,Missing Before (%),Missing After,Missing After (%)
30,FIXEDRATE,449335,84.96,449335,84.96
28,MATURITYDATE,449333,84.96,449333,84.96
31,PRODUCT_STATUS,436160,82.47,0,0.00
27,STARTDATE,436156,82.47,436156,82.47
19,CLOSURE_REASON,385328,72.86,0,0.00
22,SALARY,326649,61.76,0,0.00
18,ACCT_CLOSE_DATE,306942,58.04,306942,58.04
10,COMPLETED_FILE,239644,45.31,0,0.00
29,AMOUNT,223520,42.26,223520,42.26
25,PRODUCT,208846,39.49,0,0.00
24,PRODUCT_LINE,208846,39.49,0,0.00
23,PRODUCT_GROUP,208846,39.49,0,0.00
26,ACCOUNTNATURE,144925,27.40,0,0.00
20,ACCT_BALANCE,144925,27.40,144925,27.40
17,CURRENCY,144925,27.40,0,0.00
14,ACCT_OPENING_DATE,144925,27.40,144925,27.40
16,ACCOUNT_TYPE_DESC,144925,27.40,0,0.00
15,ACCOUNT_CATEGORY,144925,27.40,144925,27.40
4,MARITAL_STATUS,118698,22.44,0,0.00
6,DATE_OF_BIRTH,101342,19.16,101342,19.16
13,ACCOUNT_STATUS,44440,8.40,0,0.00
1,ACCOUNT_NO,44440,8.40,44440,8.40
11,LAST_REVIEW_DATE,27405,5.18,27405,5.18
12,NEXT__REVIEW_DATE,24582,4.65,24582,4.65
5,CUST_OPENING_DATE,13622,2.58,13622,2.58
9,SCORE_KYC,845,0.16,0,0.00
7,NATURE_CLIENT,78,0.01,0,0.00
0,CUSTOMER_NO,0,0.00,0,0.00
8,BRANCH,0,0.00,0,0.00
3,RESIDENCE,0,0.00,0,0.00
2,NATIONALITY,0,0.00,0,0.00
21,INDUSTRY,0,0.00,0,0.00
32,PARTYCLASS,0,0.00,0,0.00
33,LOB,0,0.00,0,0.00

## 3.6 Exact Duplicate Removal

Exact duplicate rows are removed to eliminate redundant records while preserving unique customer-account information.

Only fully duplicated rows are removed.

In [15]:
# ==========================================================
# EXACT DUPLICATE REMOVAL
# ==========================================================

rows_before = len(df_clean)

duplicates = df_clean.duplicated().sum()

df_clean = df_clean.drop_duplicates()

rows_after = len(df_clean)

removed = rows_before - rows_after

print("=" * 70)
print("EXACT DUPLICATE REMOVAL")
print("=" * 70)

print(f"Rows before     : {rows_before:,}")
print(f"Duplicate rows  : {duplicates:,}")
print(f"Rows after      : {rows_after:,}")
print(f"Removed rows    : {removed:,}")

======================================================================
EXACT DUPLICATE REMOVAL
======================================================================
Rows before     : 528,884
Duplicate rows  : 38,640
Rows after      : 490,244
Removed rows    : 38,640

In [16]:
remaining_duplicates = df_clean.duplicated().sum()

print()

print("Remaining duplicates :", remaining_duplicates)

Remaining duplicates : 0

In [17]:
display(df_clean.head())

,CUSTOMER_NO,ACCOUNT_NO,NATIONALITY,RESIDENCE,MARITAL_STATUS,CUST_OPENING_DATE,DATE_OF_BIRTH,NATURE_CLIENT,BRANCH,SCORE_KYC,COMPLETED_FILE,LAST_REVIEW_DATE,NEXT__REVIEW_DATE,ACCOUNT_STATUS,ACCT_OPENING_DATE,ACCOUNT_CATEGORY,ACCOUNT_TYPE_DESC,CURRENCY,ACCT_CLOSE_DATE,CLOSURE_REASON,ACCT_BALANCE,INDUSTRY,SALARY,PRODUCT_GROUP,PRODUCT_LINE,PRODUCT,ACCOUNTNATURE,STARTDATE,MATURITYDATE,AMOUNT,FIXEDRATE,PRODUCT_STATUS,PARTYCLASS,LOB
0,113772024,2012012858,TN,TN,M,2004-09-30,1969-05-29,PPH,5820,LR,YES,2025-09-05,2029-09-05,Closed,2019-08-27,3023.0,Crédit acquisition logement TEGF6,TND,2026-01-28,NOT_APPLICABLE,-10714.347,9000,2725.739,RT.CRD.IMMOBILERS,LENDING,RT.RT.CRD.IMMOBILERS.527,Crédit acquisition logement TEGF6,1251227.0,1290627.0,10954600.0,4.5,CURRENT,Retail,4
1,113772022,2012119377,TN,TN,M,2004-09-30,1960-09-23,PPH,5820,LR,YES,2025-09-05,2029-09-05,Closed,2026-01-05,3611.0,DEPOTS A TERME,TND,2025-06-30,NOT_APPLICABLE,0.000,9000,3300.537,ATB.PLACEMENT.NEG,DEPOSITS,ATB.CAT.NEG.SIM,DEPOTS A TERME,20260102.0,NaN,NaN,NaN,UNAUTH,Retail,4
2,113772024,2011690734,TN,TN,M,2004-09-30,1969-05-29,PPH,5820,LR,YES,2025-09-05,2029-09-05,Closed,2023-06-12,3017.0,Crédit rénovation,TND,2026-01-28,NOT_APPLICABLE,-113033.101,9000,2725.739,RT.CRD.IMMOBILERS,LENDING,RT.RT.CRD.IMMOBILERS.548,Crédit rénovation,1251227.0,1380527.0,113593077.0,4.5,CURRENT,Retail,4
3,113772024,2010054933,TN,TN,M,2004-09-30,1969-05-29,PPH,5820,LR,YES,2025-09-05,2029-09-05,Closed,2022-05-27,1011.0,Compte Allocation Touristique TND,TND,2026-01-28,NOT_APPLICABLE,0.000,9000,2725.739,ATB.GRP.CUR.ACCT,ACCOUNTS,ATB.CUR.ACCT.ALL.TOURS.CARTE,Compte Allocation Touristique TND,NaN,NaN,0.0,NaN,NOT_APPLICABLE,Retail,4
4,113772022,2011091601,TN,TN,M,2004-09-30,1960-09-23,PPH,5820,LR,YES,2025-09-05,2029-09-05,Closed,2025-07-02,3611.0,DEPOTS A TERME,TND,2025-06-30,NOT_APPLICABLE,0.000,9000,3300.537,NOT_APPLICABLE,NOT_APPLICABLE,NOT_APPLICABLE,DEPOTS A TERME,NaN,NaN,NaN,NaN,NOT_APPLICABLE,Retail,4


## 3.7 Export Clean Dataset

The cleaned dataset is exported for the next phase of feature engineering and churn modelling.

In [18]:
# ==========================================================
# 3.7 EXPORT CLEAN DATASET - CANONICAL PROJECT PATH
# ==========================================================

CLEAN_DATA_DIR = BASE_DIR / "data" / "processed"
CLEAN_DATA_DIR.mkdir(parents=True, exist_ok=True)

CLEAN_DATA_FILE = CLEAN_DATA_DIR / "customer_clean_dataset.csv"

df_clean.to_csv(
    CLEAN_DATA_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 70)
print("CLEAN DATASET EXPORTED")
print("=" * 70)
print(f"Location : {CLEAN_DATA_FILE.resolve()}")
print(f"Exists   : {CLEAN_DATA_FILE.exists()}")
print(f"Rows     : {len(df_clean):,}")
print(f"Columns  : {df_clean.shape[1]}")

======================================================================
CLEAN DATASET EXPORTED
======================================================================
Location : C:\Users\Sarra\OneDrive\Desktop\PFE_CHURN_ESB\data\processed\customer_clean_dataset.csv
Exists   : True
Rows     : 490,244
Columns  : 34

In [19]:
print("=" * 70)
print("NOTEBOOK 03 COMPLETED")
print("=" * 70)

print()
print("✔ Data types standardized")
print("✔ Missing values handled")
print("✔ Categorical variables standardized")
print("✔ Numerical variables validated")
print("✔ Exact duplicate rows removed")
print("✔ Clean dataset exported")
print()
print("Final dataset shape :", df_clean.shape)

======================================================================
NOTEBOOK 03 COMPLETED
======================================================================

✔ Data types standardized
✔ Missing values handled
✔ Categorical variables standardized
✔ Numerical variables validated
✔ Exact duplicate rows removed
✔ Clean dataset exported

Final dataset shape : (490244, 34)

In [20]:
# ==========================================================
# VERIFY EXPORTED FILE
# ==========================================================

assert CLEAN_DATA_FILE.exists(), (
    f"Clean dataset was not created: {CLEAN_DATA_FILE}"
)

verification_df = pd.read_csv(
    CLEAN_DATA_FILE,
    nrows=5,
    encoding="utf-8-sig"
)

print("Export verification successful.")
display(verification_df)

Export verification successful.

,CUSTOMER_NO,ACCOUNT_NO,NATIONALITY,RESIDENCE,MARITAL_STATUS,CUST_OPENING_DATE,DATE_OF_BIRTH,NATURE_CLIENT,BRANCH,SCORE_KYC,COMPLETED_FILE,LAST_REVIEW_DATE,NEXT__REVIEW_DATE,ACCOUNT_STATUS,ACCT_OPENING_DATE,ACCOUNT_CATEGORY,ACCOUNT_TYPE_DESC,CURRENCY,ACCT_CLOSE_DATE,CLOSURE_REASON,ACCT_BALANCE,INDUSTRY,SALARY,PRODUCT_GROUP,PRODUCT_LINE,PRODUCT,ACCOUNTNATURE,STARTDATE,MATURITYDATE,AMOUNT,FIXEDRATE,PRODUCT_STATUS,PARTYCLASS,LOB
0,113772024,2012012858,TN,TN,M,2004-09-30,1969-05-29,PPH,5820,LR,YES,2025-09-05,2029-09-05,Closed,2019-08-27,3023.0,Crédit acquisition logement TEGF6,TND,2026-01-28,NOT_APPLICABLE,-10714.347,9000,2725.739,RT.CRD.IMMOBILERS,LENDING,RT.RT.CRD.IMMOBILERS.527,Crédit acquisition logement TEGF6,1251227.0,1290627.0,10954600.0,4.5,CURRENT,Retail,4
1,113772022,2012119377,TN,TN,M,2004-09-30,1960-09-23,PPH,5820,LR,YES,2025-09-05,2029-09-05,Closed,2026-01-05,3611.0,DEPOTS A TERME,TND,2025-06-30,NOT_APPLICABLE,0.000,9000,3300.537,ATB.PLACEMENT.NEG,DEPOSITS,ATB.CAT.NEG.SIM,DEPOTS A TERME,20260102.0,NaN,NaN,NaN,UNAUTH,Retail,4
2,113772024,2011690734,TN,TN,M,2004-09-30,1969-05-29,PPH,5820,LR,YES,2025-09-05,2029-09-05,Closed,2023-06-12,3017.0,Crédit rénovation,TND,2026-01-28,NOT_APPLICABLE,-113033.101,9000,2725.739,RT.CRD.IMMOBILERS,LENDING,RT.RT.CRD.IMMOBILERS.548,Crédit rénovation,1251227.0,1380527.0,113593077.0,4.5,CURRENT,Retail,4
3,113772024,2010054933,TN,TN,M,2004-09-30,1969-05-29,PPH,5820,LR,YES,2025-09-05,2029-09-05,Closed,2022-05-27,1011.0,Compte Allocation Touristique TND,TND,2026-01-28,NOT_APPLICABLE,0.000,9000,2725.739,ATB.GRP.CUR.ACCT,ACCOUNTS,ATB.CUR.ACCT.ALL.TOURS.CARTE,Compte Allocation Touristique TND,NaN,NaN,0.0,NaN,NOT_APPLICABLE,Retail,4
4,113772022,2011091601,TN,TN,M,2004-09-30,1960-09-23,PPH,5820,LR,YES,2025-09-05,2029-09-05,Closed,2025-07-02,3611.0,DEPOTS A TERME,TND,2025-06-30,NOT_APPLICABLE,0.000,9000,3300.537,NOT_APPLICABLE,NOT_APPLICABLE,NOT_APPLICABLE,DEPOTS A TERME,NaN,NaN,NaN,NaN,NOT_APPLICABLE,Retail,4